"""empty message

Revision ID: 2538b334c039
Revises: 91bb64b27e1a
Create Date: 2025-08-14 16:40:41.986576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2538b334c039'
down_revision = '91bb64b27e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites__character', schema=None) as batch_op:
        batch_op.drop_index('ix_favourites__character_character_id')
        batch_op.drop_constraint('favourites__character_character_id_fkey', type_='foreignkey')
        batch_op.drop_column('character_id')

    with op.batch_alter_table('favourites__planet', schema=None) as batch_op:
        batch_op.drop_index('ix_favourites__planet_planet_id')
        batch_op.drop_constraint('favourites__planet_planet_id_fkey', type_='foreignkey')
        batch_op.drop_column('planet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites__planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('favourites__planet_planet_id_fkey', 'planet', ['planet_id'], ['id'])
        batch_op.create_index('ix_favourites__planet_planet_id', ['planet_id'], unique=True)

    with op.batch_alter_table('favourites__character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('favourites__character_character_id_fkey', 'character', ['character_id'], ['id'])
        batch_op.create_index('ix_favourites__character_character_id', ['character_id'], unique=True)

    # ### end Alembic commands ###
