"""empty message

Revision ID: d0d185dd4b01
Revises: 2538b334c039
Create Date: 2025-08-14 16:45:36.979365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d185dd4b01'
down_revision = '2538b334c039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites__character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_favourites__character_character_id'), ['character_id'], unique=True)
        batch_op.create_foreign_key(None, 'character', ['character_id'], ['id'])

    with op.batch_alter_table('favourites__planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_favourites__planet_planet_id'), ['planet_id'], unique=True)
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites__planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_favourites__planet_planet_id'))
        batch_op.drop_column('planet_id')

    with op.batch_alter_table('favourites__character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_favourites__character_character_id'))
        batch_op.drop_column('character_id')

    # ### end Alembic commands ###
